"""
Adobe Stock Portal 上傳輔助模組

使用 Playwright 驅動 contributor.stock.adobe.com 網頁上傳流程。
專門為 Adobe Stock Contributor Portal 設計，不支援其他平台。

流程：
  1. 登入（cookie 持久化、手動 2FA/passkey 節點）
  2. 上傳檔案（file input / 找到已上傳的待填資產）
  3. 自動填入 metadata（title, keywords, Generative AI checkbox）
  4. 提交確認 — 由使用者在瀏覽器中手動點擊 Submit All

人工確認節點（blocking）：
  NODE_LOGIN    — 需要使用者完成 Passkey / email 驗證
  NODE_UPLOAD   — 卡片上傳完成，確認無錯誤
  NODE_SUBMIT   — metadata 填完，等候使用者檢查並提交
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm

from .config import get_config
from .metadata import ImageMetadata

console = Console()

# ── Confirmation node types ──────────────────────────────

NODE_LOGIN = "login"
NODE_UPLOAD = "upload"
NODE_SUBMIT = "submit"


# ── Selector presets for Adobe Stock Contributor Portal ──

# These selectors target the Adobe Stock contributor upload page.
# The structure changes periodically — tune via debug / browser_vision.

ADOBE_SELECTORS = {
    "email_input": [
        "input[type='email']",
        "input[name='email']",
        "input[id*='email']",
        "input[autocomplete='email']",
    ],
    "password_input": [
        "input[type='password']",
        "input[name='password']",
        "input[id*='password']",
    ],
    "submit_button": [
        "button[type='submit']",
        "input[type='submit']",
        "button:has-text('Continue')",
        "button:has-text('Sign in')",
        "button:has-text('Sign In')",
    ],
    "file_input": [
        "input[type='file']",
    ],
    "dropzone": [
        "div[data-test-id='upload-dropzone']",
        "div[class*='dropzone']",
        "div[aria-label*='upload' i]",
    ],
    "upload_spinner": [
        "div[class*='spinner']",
        "div[class*='progress']",
        "div[role='progressbar']",
        "div[aria-busy='true']",
        "svg[class*='spinner']",
    ],
    "title_input": [
        "input[data-test-id='title-input']",
        "input[placeholder*='Title' i]",
        "input[name='title']",
        "input[id*='title']",
        "input[aria-label*='title' i]",
    ],
    "keywords_input": [
        "textarea[data-test-id='keywords-input']",
        "textarea[placeholder*='keyword' i]",
        "input[placeholder*='keyword' i]",
        "textarea[name='keywords']",
        "textarea[id*='keyword']",
        "textarea[aria-label*='keyword' i]",
    ],
    "ai_checkbox": [
        "input[data-test-id='generative-ai-checkbox']",
        "label:has-text('Generative AI') input[type='checkbox']",
        "label:has-text('Created using generative') input[type='checkbox']",
        "label:has-text('AI') input[type='checkbox']",
        "label:has-text('Generated by AI') input[type='checkbox']",
        "input[aria-label*='generative ai' i]",
    ],
    "asset_tile": [
        "div[class*='asset']",
        "div[class*='thumbnail']",
        "div[class*='file-tile']",
        "div[data-test-id*='asset']",
        "figure",
    ],
    "upload_ready_indicator": [
        "text=Add to portfolio",
        "text=Edit details",
        "text=Submit all",
        "text=Submit All",
    ],
}


# ── Helper: find first visible element ────────────────────


def _find_visible(page, selectors: list[str], timeout: int = 5000):
    """Try each Playwright locator selector, return first visible element (or None)."""
    for sel in selectors:
        try:
            el = page.locator(sel).first
            if el.is_visible(timeout=timeout):
                return el
        except Exception:
            continue
    return None


# ── Manual confirmation node ──────────────────────────────


def confirm_node(node_type: str, message: str, timeout_minutes: int = 5):
    """
    Blocking confirmation node — pauses automation, waits for user
    to complete an action in the browser and confirm via terminal.
    """
    border = {"login": "yellow", "upload": "blue", "submit": "green"}
    style = border.get(node_type, "yellow")

    console.print()
    console.print(
        Panel.fit(
            f"[bold]⚠ Manual Action Required — {node_type}[/bold]\n\n"
            f"{message}\n\n"
            f"[dim]⏱ Timeout: {timeout_minutes} minutes[/dim]",
            border_style=style,
        )
    )
    console.print(f"  [bold]{'─' * 50}[/bold]")

    for tick in range(timeout_minutes * 12):
        done = Confirm.ask(
            "  [bold]▶ Press 'y' when done, 'n' to abort[/bold]",
            default=False,
        )
        if done:
            console.print("  [green]✓ Continuing...[/green]")
            return
        console.print("  [dim]Waiting... (check the browser window)[/dim]")

    console.print("[red]✗ Timeout waiting for manual confirmation.[/red]")
    raise TimeoutError(f"Manual confirmation node '{node_type}' timed out")


# ── Cookie persistence helpers ────────────────────────────


def _get_cookie_path() -> Path:
    cfg = get_config()
    return Path(cfg.browser.cookie_cache)


def _save_cookies(context):
    path = _get_cookie_path()
    try:
        cookies = context.cookies()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(cookies, indent=2))
        console.print(f"  [dim]Saved {len(cookies)} cookies[/dim]")
    except Exception:
        pass


def _load_cookies(context):
    path = _get_cookie_path()
    if path.exists():
        try:
            cookies = json.loads(path.read_text())
            context.add_cookies(cookies)
            console.print(f"  [dim]Restored {len(cookies)} cookies from cache[/dim]")
            return True
        except (json.JSONDecodeError, Exception) as e:
            console.print(f"  [dim]Cookie cache read error: {e}[/dim]")
    return False


# ── The Upload Assistant Module ────────────────────────────


@dataclass
class UploadResult:
    """Result summary after the portal pipeline runs."""

    logged_in: bool = False
    files_uploaded: int = 0
    metadata_filled: int = 0
    total_assets: int = 0


class AdobePortalUpload:
    """
    Adobe Stock Contributor Portal upload assistant.

    Sync context manager. Uses Playwright to drive the real browser.

    Usage:
        with AdobePortalUpload() as portal:
            portal.login(email="...", password="...")
            portal.upload_files(["/path/img1.jpg", ...])
            portal.fill_metadata(metadata_list)
            # user clicks Submit All in browser
    """

    def __init__(self, headless: bool = False, slow_mo: int = 500):
        cfg = get_config().browser
        self.headless = headless or cfg.headless
        self.slow_mo = slow_mo or cfg.slow_mo
        self.upload_url = cfg.submit_url

        self._pw = None
        self._browser = None
        self._context = None
        self._page = None

    # ── Context manager ────────────────────────────────────

    def __enter__(self) -> "AdobePortalUpload":
        console.print(
            Panel.fit(
                "[bold]Adobe Stock Portal Upload Assistant[/bold]",
                border_style="cyan",
            )
        )
        self._start_playwright()
        return self

    def __exit__(self, *args):
        self._save_cookies()
        if self._context:
            try:
                self._context.close()
            except Exception:
                pass
        if self._browser:
            try:
                self._browser.close()
            except Exception:
                pass
        if self._pw:
            try:
                self._pw.stop()
            except Exception:
                pass
        console.print("[dim]Portal browser closed.[/dim]")

    # ── Internal: start Playwright ─────────────────────────

    def _start_playwright(self):
        from playwright.sync_api import sync_playwright

        self._pw = sync_playwright().start()
        self._browser = self._pw.chromium.launch(
            headless=self.headless,
            slow_mo=self.slow_mo,
        )
        self._context = self._browser.new_context(
            viewport={"width": 1440, "height": 900},
            user_agent=(
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/134.0.0.0 Safari/537.36"
            ),
        )
        _load_cookies(self._context)
        self._page = self._context.new_page()
        console.print("  [green]✓[/green] Playwright browser ready")

    def _save_cookies(self):
        if self._context:
            _save_cookies(self._context)

    # ── LOGIN ──────────────────────────────────────────────

    def login(self, email: str = "", password: str = "") -> bool:
        """
        Navigate to the contributor upload page.

        If cached cookies are still valid, skip straight to the upload page.
        If not, fill email/password (if provided) and then show a
        confirmation node for any 2FA / passkey / email verification.
        """
        page = self._page
        cfg = get_config().adobe.contributor
        cred_email = email or cfg.email
        cred_password = password or cfg.password

        console.print(f"\n[bold]🔑 Login: Adobe Stock Contributor[/bold]")
        console.print(f"  URL: {self.upload_url}")

        page.goto(self.upload_url, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # ── Already logged in? ──
        current_url = page.url.lower()
        if "uploads" in current_url or "dashboard" in current_url:
            console.print("  [green]✓[/green] Already logged in (cached session)")
            return True

        # Check for logged-in indicators on the page
        try:
            body = page.locator("body").inner_text(timeout=2000)
            if any(ind in body.lower() for ind in ["logout", "sign out", "my portfolio"]):
                console.print("  [green]✓[/green] Session valid (logged-in indicator)")
                return True
        except Exception:
            pass

        console.print("  [yellow]Login required[/yellow]")

        # ── Fill email if we're on the Adobe auth page ──
        if "auth.services.adobe.com" in current_url or "adobelogin" in current_url:
            if cred_email:
                email_el = _find_visible(page, ADOBE_SELECTORS["email_input"])
                if email_el:
                    email_el.fill(cred_email)
                    console.print("  ✓ Email filled")

                submit_el = _find_visible(page, ADOBE_SELECTORS["submit_button"])
                if submit_el:
                    submit_el.click()
                    page.wait_for_timeout(3000)
                    console.print("  ✓ Login form submitted")
            else:
                console.print("  [yellow]No email configured — manual input required[/yellow]")

            # ── Fill password if we advanced to password field ──
            pass_el = _find_visible(page, ADOBE_SELECTORS["password_input"])
            if pass_el and cred_password:
                pass_el.fill(cred_password)
                console.print("  ✓ Password filled")
                submit_el = _find_visible(page, ADOBE_SELECTORS["submit_button"])
                if submit_el:
                    submit_el.click()
                    page.wait_for_timeout(3000)
                    console.print("  ✓ Password submitted")

            # ── Check if we hit a challenge (passkey / 2FA / email code) ──
            challenge_keywords = [
                "passkey", "verify", "verification", "authenticator",
                "mfa", "2fa", "otp", "code", "authenticate",
                "認証", "確認", "驗證",
            ]

            is_challenge = any(kw in page.url.lower() for kw in challenge_keywords)
            if not is_challenge:
                try:
                    body = page.locator("body").inner_text(timeout=2000)
                    is_challenge = any(kw in body.lower() for kw in challenge_keywords)
                except Exception:
                    pass

            if is_challenge:
                console.print("  [yellow]⚠ Security challenge detected[/yellow]")
                confirm_node(
                    NODE_LOGIN,
                    "Adobe requires additional verification (passkey / email code / 2FA).\n"
                    "  • Check the browser window\n"
                    "  • Complete the verification\n"
                    "  • Wait until the contributor upload page loads",
                    timeout_minutes=5,
                )
            else:
                # Wait a moment for redirect
                page.wait_for_timeout(5000)

        # ── Check final login state ──
        current_url = page.url.lower()
        if "uploads" in current_url or "dashboard" in current_url:
            console.print("  [green]✓[/green] Login successful!")
            self._save_cookies()
            return True

        # Try navigating to upload page in case we're already in
        try:
            page.goto(self.upload_url, wait_until="domcontentloaded")
            page.wait_for_timeout(3000)
            if "uploads" in page.url.lower():
                console.print("  [green]✓[/green] Login confirmed (redirected!)")
                self._save_cookies()
                return True
        except Exception:
            pass

        # ── Last resort: manual login node ──
        confirm_node(
            NODE_LOGIN,
            "Could not detect login completion automatically.\n"
            "  • Go to the browser window\n"
            "  • Complete the login process manually\n"
            "  • Navigate to the upload page\n"
            "  • Then confirm to continue",
            timeout_minutes=5,
        )

        if "uploads" in page.url.lower():
            console.print("  [green]✓[/green] Login confirmed!")
            self._save_cookies()
            return True

        console.print("  [yellow]⚠ Login status uncertain — continuing anyway[/yellow]")
        return False

    # ── FILE UPLOAD ─────────────────────────────────────────

    def upload_files(self, file_paths: list[str]) -> int:
        """
        Upload image files via the Adobe Stock Contributor Portal.

        Returns the number of files successfully uploaded.
        """
        page = self._page
        console.print(f"\n[bold]📤 Upload: {len(file_paths)} files[/bold]")

        # Navigate to upload URL if not already there
        if "uploads" not in page.url.lower():
            page.goto(self.upload_url, wait_until="domcontentloaded")
            page.wait_for_timeout(3000)

        # Validate files
        valid = [str(Path(p).resolve()) for p in file_paths if Path(p).exists()]
        if not valid:
            console.print("  [red]No valid files to upload[/red]")
            return 0

        missing = len(file_paths) - len(valid)
        if missing:
            console.print(f"  [yellow]⚠ {missing} file(s) not found, skipped[/yellow]")

        # ── Try file input ──
        file_input = _find_visible(page, ADOBE_SELECTORS["file_input"])
        if file_input:
            try:
                file_input.set_input_files(valid)
                console.print("  [green]✓[/green] Files queued via file input")
                page.wait_for_timeout(2000)
                return len(valid)
            except Exception as e:
                console.print(f"  [yellow]File input error: {e}[/yellow]")

        # ── Try drop zone ──
        dropzone = _find_visible(page, ADOBE_SELECTORS["dropzone"])
        if dropzone:
            try:
                inner = dropzone.locator("input[type='file']").first
                if inner.is_visible(timeout=2000):
                    inner.set_input_files(valid)
                    console.print("  [green]✓[/green] Files queued via drop zone")
                    page.wait_for_timeout(2000)
                    return len(valid)
                else:
                    console.print(
                        "  [yellow]Drop zone visible but file input not exposed.\n"
                        "  Drag files into the browser window manually.[/yellow]"
                    )
                    return 0
            except Exception as e:
                console.print(f"  [yellow]Drop zone error: {e}[/yellow]")

        console.print("  [yellow]⚠ No upload area found — files may already exist[/yellow]")
        return 0

    def wait_for_upload_complete(self, timeout_sec: int = 120) -> bool:
        """Wait for upload processing spinners to disappear."""
        page = self._page
        console.print("  Waiting for upload to complete...", end="")
        for _ in range(timeout_sec):
            spinner = _find_visible(page, ADOBE_SELECTORS["upload_spinner"], timeout=1000)
            if not spinner:
                console.print(" [green]done[/green]")
                return True
            console.print(".", end="")
            page.wait_for_timeout(1000)
        console.print(" [yellow]timeout[/yellow]")
        return False

    # ── METADATA FILL ──────────────────────────────────────

    def fill_metadata(self, metadata_list: list[ImageMetadata]) -> int:
        """
        Auto-fill metadata for each uploaded asset.

        For each asset:
          1. Click the asset tile
          2. Fill title (max 200 chars)
          3. Fill keywords (comma-separated)
          4. Check the "Generative AI" disclosure checkbox
          5. Move to next asset

        Returns count of successfully filled assets.
        """
        page = self._page
        console.print(f"\n[bold]🏷️  Metadata: {len(metadata_list)} assets[/bold]")

        success = 0
        for idx, meta in enumerate(metadata_list):
            console.print(f"\n  [{idx + 1}/{len(metadata_list)}] {meta.filename}")

            # ── Click the asset tile ──
            tile_clicked = False
            for sel in ADOBE_SELECTORS["asset_tile"]:
                try:
                    tile = page.locator(sel).filter(has_text=meta.filename.split(".")[0]).first
                    if tile.is_visible(timeout=2000):
                        tile.click()
                        page.wait_for_timeout(1500)
                        tile_clicked = True
                        break
                except Exception:
                    continue

            if not tile_clicked:
                console.print("  [yellow]⚠ Asset tile not found, trying file name...[/yellow]")
                try:
                    el = page.locator(f"text={meta.filename}").first
                    if el.is_visible(timeout=2000):
                        el.click()
                        page.wait_for_timeout(1500)
                except Exception:
                    console.print("  [yellow]⚠ Could not locate asset — skipping[/yellow]")
                    continue

            # ── Title ──
            _fill_field(page, ADOBE_SELECTORS["title_input"], meta.title[:200], "Title")

            # ── Keywords ──
            kw_text = ", ".join(meta.keywords) if isinstance(meta.keywords, list) else str(meta.keywords)
            _fill_field(page, ADOBE_SELECTORS["keywords_input"], kw_text, "Keywords")

            # ── AI checkbox ──
            if meta.ai_generated:
                _check_ai_box(page)

            console.print(f"  [green]✓[/green] {meta.filename} done")
            success += 1

        return success

    # ── FULL PIPELINE ──────────────────────────────────────

    def run(
        self,
        metadata_list: list[ImageMetadata],
        file_paths: list[str] | None = None,
        email: str = "",
        password: str = "",
        skip_upload: bool = False,
        skip_metadata: bool = False,
    ) -> UploadResult:
        """
        Full Adobe Stock Portal pipeline:

          1. Login (auto or manual)
          2. Upload files (if provided)
          3. Auto-fill metadata
          4. Submit confirmation node

        Returns UploadResult summary.
        """
        result = UploadResult(total_assets=len(metadata_list))

        # Step 1: Login
        logged_in = self.login(email=email, password=password)
        result.logged_in = logged_in

        # Step 2: Upload files
        if file_paths and not skip_upload:
            uploaded = self.upload_files(file_paths)
            result.files_uploaded = uploaded
            if uploaded > 0:
                self.wait_for_upload_complete()

            confirm_node(
                NODE_UPLOAD,
                "Files have been uploaded via the browser.\n"
                "  • Check that all files appear in the portal\n"
                "  • Ensure there are no error messages\n"
                "  • If files are missing, drag them in manually",
                timeout_minutes=5,
            )

        # Step 3: Fill metadata
        if metadata_list and not skip_metadata:
            filled = self.fill_metadata(metadata_list)
            result.metadata_filled = filled

        # Step 4: Submit confirmation
        confirm_node(
            NODE_SUBMIT,
            "Metadata has been filled for all assets.\n"
            "  • Review each asset in the browser\n"
            "  • Verify title, keywords, and AI tag are correct\n"
            "  • Click 'Submit All' / 'Add to portfolio' when ready\n"
            "  • Assets are NOT submitted until you do this",
            timeout_minutes=10,
        )

        console.print(f"\n[bold green]✓ Adobe Stock Portal pipeline complete[/bold green]")
        console.print(f"  Files uploaded:  {result.files_uploaded}")
        console.print(f"  Metadata filled: {result.metadata_filled}/{result.total_assets}")

        return result


# ── Internal helpers ──────────────────────────────────────


def _fill_field(page, selectors: list[str], value: str, name: str = "field") -> bool:
    """Find a visible field by selector list, click it, clear it, type the value."""
    el = _find_visible(page, selectors)
    if el:
        try:
            el.click()
            el.fill("")
            el.fill(value)
            return True
        except Exception as e:
            console.print(f"  [yellow]⚠ {name} fill error: {e}[/yellow]")
            return False
    console.print(f"  [yellow]⚠ {name} field not found[/yellow]")
    return False


def _check_ai_box(page):
    """Find and check the Generative AI disclosure checkbox."""
    el = _find_visible(page, ADOBE_SELECTORS["ai_checkbox"])
    if el:
        try:
            if not el.is_checked():
                el.click()
                console.print("  ✓ AI Generated: checked")
            else:
                console.print("  ✓ AI Generated: already checked")
        except Exception:
            console.print("  [yellow]⚠ Could not toggle AI checkbox[/yellow]")
    else:
        console.print("  [yellow]⚠ AI checkbox not found[/yellow]")
