"""
CloakBrowser 上傳模組 — 登入、上傳流程、人工確認節點

使用 CloakBrowser（stealth Chromium）繞過 bot 偵測，驅動各圖庫平台的
網頁上傳流程。支援 PIXTA（日系）、Adobe Stock 等平台。

流程：
  登入（cookie 持久化） → 上傳檔案 → 填寫 Metadata → 人工確認

人工確認節點（blocking）：
  NODE_LOGIN：需要使用者手動完成 2FA / email 驗證
  NODE_UPLOAD：檔案上傳完成，等待使用者檢查
  NODE_SUBMIT：Metadata 填完，等待使用者手動點 Submit
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Optional

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm

console = Console()

# ── Manual Confirmation Node Types ───────────────────────────

CONFIRM_NODE_LOGIN = "login"
CONFIRM_NODE_UPLOAD = "upload"
CONFIRM_NODE_SUBMIT = "submit"


# ── Platform Definitions ─────────────────────────────────────

@dataclass
class PlatformConfig:
    """Platform-specific configuration for CloakBrowser automation."""

    name: str
    login_url: str
    upload_url: str
    cookie_cache: str

    email_selector: list[str] = field(default_factory=lambda: [
        "input[type='email']",
        "input[name='email']",
        "input[id*='email']",
        "input[autocomplete='email']",
        "input[placeholder*='email' i]",
        "input[placeholder*='mail' i]",
        "input[placeholder*='メール']",
    ])
    password_selector: list[str] = field(default_factory=lambda: [
        "input[type='password']",
        "input[name='password']",
        "input[id*='password']",
        "input[autocomplete='current-password']",
    ])
    submit_button_selector: list[str] = field(default_factory=lambda: [
        "button[type='submit']",
        "input[type='submit']",
        "button:has-text('Sign In')",
        "button:has-text('Log In')",
        "button:has-text('Login')",
        "button:has-text('ログイン')",
    ])

    login_success_indicator: list[str] = field(default_factory=lambda: [
        "upload", "dashboard", "mypage", "contributor",
    ])

    file_input_selector: list[str] = field(default_factory=lambda: [
        "input[type='file']",
        "input[accept*='image']",
        "input[accept*='jpg']",
        "input[accept*='jpeg']",
        "input[accept*='png']",
    ])
    upload_dropzone_selector: list[str] = field(default_factory=lambda: [
        "div[data-test-id='upload-dropzone']",
        "div[class*='dropzone']",
        "div[class*='upload']",
        "div[aria-label*='upload' i]",
        "div:has-text('Upload')",
        "div:has-text('upload')",
        "section[class*='upload']",
    ])
    upload_spinner_selector: list[str] = field(default_factory=lambda: [
        "div[class*='spinner']",
        "div[class*='progress']",
        "div[aria-busy='true']",
        "div[role='progressbar']",
        "svg[class*='spinner']",
    ])

    title_selector: list[str] = field(default_factory=lambda: [
        "input[data-test-id='title-input']",
        "input[placeholder*='Title' i]",
        "input[name='title']",
        "input[id*='title']",
        "input[aria-label*='title' i]",
        "textarea[placeholder*='title' i]",
        "textarea[aria-label*='title' i]",
        "textarea[data-test-id='title-input']",
    ])
    keywords_selector: list[str] = field(default_factory=lambda: [
        "textarea[data-test-id='keywords-input']",
        "textarea[placeholder*='keyword' i]",
        "input[placeholder*='keyword' i]",
        "textarea[name='keywords']",
        "textarea[id*='keyword']",
        "textarea[aria-label*='keyword' i]",
        "div[class*='keywords'] textarea",
        "div[class*='keyword'] input",
    ])
    ai_checkbox_selector: list[str] = field(default_factory=lambda: [
        "input[data-test-id='generative-ai-checkbox']",
        "label:has-text('Generative AI') input[type='checkbox']",
        "label:has-text('Created using generative') input[type='checkbox']",
        "label:has-text('AI') input[type='checkbox']",
        "label:has-text('AI生成') input[type='checkbox']",
        "label:has-text('Generated by AI') input[type='checkbox']",
        "input[aria-label*='generative ai' i]",
        "input[aria-label*='AI' i]",
        "span:has-text('Generative AI') input[type='checkbox']",
    ])
    asset_tile_selector: list[str] = field(default_factory=lambda: [
        "div[class*='asset']",
        "div[class*='thumbnail']",
        "div[class*='file-tile']",
        "img[class*='thumbnail']",
        "figure",
        "li[class*='file']",
        "div[data-test-id*='asset']",
    ])


# ── Platform Presets ────────────────────────────────────────

ADOBE_STOCK_CONFIG = PlatformConfig(
    name="adobe-stock",
    login_url="https://contributor.stock.adobe.com/en/uploads",
    upload_url="https://contributor.stock.adobe.com/en/uploads",
    cookie_cache="./.cookies/adobe_stock_cloak.json",
)

FREEPIK_CONFIG = PlatformConfig(
    name="freepik",
    login_url="https://contributor.freepik.com/",
    upload_url="https://contributor.freepik.com/files",
    cookie_cache="./.cookies/freepik_cloak.json",
    login_success_indicator=["files", "dashboard", "contributor"],
)

PLATFORMS: dict[str, PlatformConfig] = {
    "adobe-stock": ADOBE_STOCK_CONFIG,
    "freepik": FREEPIK_CONFIG,
}


# ── CloakBrowser Uploader ───────────────────────────────────

class CloakUploader:
    """
    CloakBrowser-based uploader for stock photo contributor platforms.

    Sync context manager. Usage:

        with CloakUploader(platform="adobe-stock") as uploader:
            uploader.login(email="...", password="...")
            uploader.upload_files(["/path/to/img1.jpg", ...])
            uploader.fill_metadata(metadata_list)
            # User clicks Submit manually
    """

    def __init__(
        self,
        platform: str = "adobe-stock",
        headless: bool = False,
        slow_mo: int = 500,
        cookie_cache: str | None = None,
        humanize: bool = True,
    ):
        if platform not in PLATFORMS:
            raise ValueError(
                f"Unknown platform: {platform}. Choose: {list(PLATFORMS.keys())}"
            )
        self.platform_name = platform
        self.cfg = PLATFORMS[platform]
        self.headless = headless
        self.slow_mo = slow_mo
        self.humanize = humanize
        self.cookie_path = Path(cookie_cache or self.cfg.cookie_cache)

        self._browser = None
        self._context = None
        self._page = None

    # ── Context Manager ───────────────────────────────────────

    def __enter__(self) -> "CloakUploader":
        console.print(
            Panel.fit(
                f"[bold]CloakBrowser: {self.cfg.name}[/bold]",
                border_style="cyan",
            )
        )
        self._start_browser()
        return self

    def __exit__(self, *args):
        self._save_cookies()
        if self._context:
            try:
                self._context.close()
            except Exception:
                pass
        if self._browser:
            try:
                self._browser.close()
            except Exception:
                pass
        console.print("[dim]CloakBrowser closed.[/dim]")

    # ── Browser Lifecycle ────────────────────────────────────

    def _start_browser(self):
        """Launch CloakBrowser and create a persistent context."""
        from cloakbrowser import launch
        from playwright.sync_api import expect

        self._browser = launch(
            headless=self.headless,
            humanize=self.humanize,
            geoip=True,
        )

        self._context = self._browser.new_context(
            viewport={"width": 1440, "height": 900},
            user_agent=(
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/132.0.0.0 Safari/537.36"
            ),
        )

        # Restore cached cookies
        if self.cookie_path.exists():
            try:
                cookies = json.loads(self.cookie_path.read_text())
                self._context.add_cookies(cookies)
                console.print(f"  [dim]Restored {len(cookies)} cookies from cache[/dim]")
            except (json.JSONDecodeError, Exception) as e:
                console.print(f"  [dim]Cookie cache read error: {e}[/dim]")

        self._page = self._context.new_page()
        console.print("  [green]✓[/green] CloakBrowser ready")

    def _save_cookies(self):
        """Persist cookies to disk."""
        if self._context:
            try:
                cookies = self._context.cookies()
                self.cookie_path.parent.mkdir(parents=True, exist_ok=True)
                self.cookie_path.write_text(json.dumps(cookies, indent=2))
                console.print(f"  [dim]Saved {len(cookies)} cookies[/dim]")
            except Exception:
                pass

    # ── Helper: find first visible element ────────────────────

    def _find_visible(self, selectors: list[str], timeout: int = 5000):
        """Try each selector and return the first visible element (or None)."""
        for sel in selectors:
            try:
                el = self._page.locator(sel).first
                if el.is_visible(timeout=timeout):
                    return el
            except Exception:
                continue
        return None

    def _wait_for_url(self, indicators: list[str], timeout_sec: int = 120) -> bool:
        """Wait for page URL to contain one of the indicators."""
        for _ in range(timeout_sec):
            current = self._page.url.lower()
            if any(ind.lower() in current for ind in indicators):
                return True
            self._page.wait_for_timeout(1000)
        return False

    # ── CONFIRMATION NODE ─────────────────────────────────────

    def confirm_node(
        self,
        node_type: str,
        message: str,
        timeout_minutes: int = 5,
    ) -> None:
        """
        Blocking manual confirmation node.

        Pauses automation and waits for the user to complete an action
        in the browser window, then confirms to continue.
        """
        border = {"login": "yellow", "upload": "blue", "submit": "green"}
        style = border.get(node_type, "yellow")

        console.print()
        console.print(Panel.fit(
            f"[bold]⚠ Manual Action Required — {node_type}[/bold]\n\n"
            f"{message}\n\n"
            f"[dim]⏱ Timeout: {timeout_minutes} minutes[/dim]",
            border_style=style,
        ))
        console.print(f"  [bold]{'─' * 50}[/bold]")

        for _ in range(timeout_minutes * 12):
            done = Confirm.ask(
                "  [bold]▶ Press 'y' when done, 'n' to abort[/bold]",
                default=False,
            )
            if done:
                console.print("  [green]✓ Continuing...[/green]")
                return
            console.print("  [dim]Waiting... (check the browser window)[/dim]")

        console.print("[red]✗ Timeout waiting for manual confirmation.[/red]")
        raise TimeoutError(f"Manual confirmation node '{node_type}' timed out")

    # ── LOGIN ────────────────────────────────────────────────

    def login(self, email: str = "", password: str = "", skip_if_logged_in: bool = True) -> bool:
        """
        Login to the contributor platform.

        Flow:
          1. Navigate to upload/login page
          2. If already logged in (cached cookies valid) → return True
          3. If not → fill email/password if provided
          4. If 2FA/challenge detected → show CONFIRM_NODE_LOGIN
          5. Save cookies
        """
        page = self._page
        console.print(f"\n[bold]🔑 Login: {self.cfg.name}[/bold]")

        page.goto(self.cfg.login_url, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # ── Check if already logged in ──
        current_url = page.url.lower()
        if skip_if_logged_in:
            for indicator in self.cfg.login_success_indicator:
                if indicator.lower() in current_url:
                    console.print(f"  [green]✓[/green] Already logged in (cached session)")
                    return True

        if skip_if_logged_in:
            try:
                body_text = page.locator("body").inner_text(timeout=3000)
                if any(ind in body_text.lower() for ind in ["logout", "sign out", "ログアウト", "my page", "マイページ"]):
                    console.print(f"  [green]✓[/green] Session valid (logged-in indicator found)")
                    return True
            except Exception:
                pass

        # ── Fill login form ──
        if email and password:
            email_el = self._find_visible(self.cfg.email_selector)
            if email_el:
                email_el.fill(email)
                console.print("  ✓ Email filled")

            pass_el = self._find_visible(self.cfg.password_selector)
            if pass_el:
                pass_el.fill(password)
                console.print("  ✓ Password filled")

            submit_el = self._find_visible(self.cfg.submit_button_selector)
            if submit_el:
                submit_el.click()
                console.print("  ✓ Email submitted, waiting for password field to load...")
                # Wait for password input to appear (up to 10 seconds)
                for _ in range(20):
                    pass_el = self._find_visible(self.cfg.password_selector, timeout=500)
                    if pass_el:
                        break
                    page.wait_for_timeout(500)
                console.print("  ✓ Login form submitted")
        else:
            console.print("  [yellow]No credentials provided — will wait for manual login[/yellow]")

        # ── Check if login succeeded ──
        current_url = page.url.lower()
        for indicator in self.cfg.login_success_indicator:
            if indicator in current_url:
                console.print("  [green]✓[/green] Login successful!")
                self._save_cookies()
                return True

        # ── Check for 2FA / challenge ──
        challenge_detected = False
        challenge_keywords = [
            "passkey", "verify", "verification", "authentication",
            "authenticator", "mfa", "2fa", "otp", "code",
            "認証", "確認", "驗證",
        ]
        body_text = ""
        try:
            body_text = page.locator("body").inner_text(timeout=2000)
        except Exception:
            pass

        for kw in challenge_keywords:
            if kw in page.url.lower() or kw in body_text.lower():
                challenge_detected = True
                break

        # ── CONFIRMATION NODE: Manual Login ──
        message_lines = ["Complete login in the browser window."]
        if not email:
            message_lines.append("  • Enter your credentials")
        if challenge_detected:
            message_lines.append("  • Complete 2FA / email verification / passkey")
        message_lines.append("  • Wait until the upload/submit page loads")

        self.confirm_node(
            CONFIRM_NODE_LOGIN,
            "\n".join(message_lines),
            timeout_minutes=5,
        )

        # Check login status after confirmation
        for indicator in self.cfg.login_success_indicator:
            if indicator in page.url.lower():
                console.print("  [green]✓[/green] Login confirmed!")
                self._save_cookies()
                return True

        try:
            page.goto(self.cfg.upload_url, wait_until="domcontentloaded")
            page.wait_for_timeout(3000)
            for indicator in self.cfg.login_success_indicator:
                if indicator in page.url.lower():
                    console.print("  [green]✓[/green] Login confirmed (redirected)!")
                    self._save_cookies()
                    return True
        except Exception:
            pass

        console.print("[yellow]⚠ Could not confirm login. Continuing anyway...[/yellow]")
        return False

    # ── FILE UPLOAD ───────────────────────────────────────────

    def upload_files(
        self,
        file_paths: list[str],
        upload_done_callback: Callable | None = None,
    ) -> int:
        """
        Upload files via the contributor web interface.
        Returns number of files uploaded.
        """
        page = self._page
        console.print(f"\n[bold]📤 Upload: {len(file_paths)} files[/bold]")

        # Navigate to upload page if not already there
        if self.cfg.upload_url.lower() not in page.url.lower():
            page.goto(self.cfg.upload_url, wait_until="domcontentloaded")
            page.wait_for_timeout(3000)

        # Validate files exist
        valid_paths = []
        for fp in file_paths:
            p = Path(fp)
            if p.exists():
                valid_paths.append(str(p.resolve()))
            else:
                console.print(f"  [red]✗ File not found: {fp}[/red]")

        if not valid_paths:
            console.print("[red]No valid files to upload.[/red]")
            return 0

        # ── Try file input ──
        file_input = self._find_visible(self.cfg.file_input_selector)
        if file_input:
            console.print(f"  Uploading {len(valid_paths)} files via file input...")
            try:
                file_input.set_input_files(valid_paths)
                console.print("  [green]✓[/green] Files queued for upload")
                page.wait_for_timeout(3000)
            except Exception as e:
                console.print(f"  [yellow]File input error: {e}[/yellow]")
                file_input = None

        # ── Try drop zone (fallback) ──
        if not file_input:
            dropzone = self._find_visible(self.cfg.upload_dropzone_selector)
            if dropzone:
                console.print("  Drop zone found. Trying inner file input...")
                try:
                    inner = dropzone.locator("input[type='file']").first
                    if inner.is_visible(timeout=2000):
                        inner.set_input_files(valid_paths)
                        console.print("  [green]✓[/green] Files queued via drop zone")
                    else:
                        console.print("  [yellow]⚠ Drop zone visible but file input not accessible.[/yellow]")
                except Exception as e:
                    console.print(f"  [yellow]Drop zone error: {e}[/yellow]")
            else:
                console.print("  [yellow]⚠ No upload area found[/yellow]")

        # ── Wait for upload to complete ──
        console.print("  Waiting for upload to complete...", end="")
        spinner = None
        for sel in self.cfg.upload_spinner_selector:
            try:
                spinner = page.locator(sel).first
                if spinner.is_visible(timeout=2000):
                    break
            except Exception:
                spinner = None

        if spinner:
            for _ in range(120):
                try:
                    if not spinner.is_visible(timeout=1000):
                        console.print(" [green]done[/green]")
                        break
                except Exception:
                    console.print(" [green]done[/green]")
                    break
                console.print(".", end="")
                page.wait_for_timeout(1000)
            else:
                console.print(" [yellow]timeout (continuing)[/yellow]")
        else:
            page.wait_for_timeout(5000)
            console.print(" [green]ok[/green]")

        if upload_done_callback:
            upload_done_callback(valid_paths)

        return len(valid_paths)

    # ── METADATA FILL ─────────────────────────────────────────

    def _fill_field(self, selectors: list[str], value: str, field_name: str = "field") -> bool:
        el = self._find_visible(selectors)
        if el:
            try:
                el.click()
                el.fill("")
                el.fill(value)
                return True
            except Exception as e:
                console.print(f"  [yellow]⚠ {field_name} fill error: {e}[/yellow]")
                return False
        console.print(f"  [yellow]⚠ {field_name} field not found[/yellow]")
        return False

    def fill_metadata(
        self,
        metadata_list: list,
        title_field: str = "title",
        keywords_field: str = "keywords",
        ai_generated: bool = True,
    ) -> int:
        """
        Fill metadata for each uploaded asset.
        Returns count of successfully filled assets.
        """
        page = self._page
        console.print(f"\n[bold]🏷️  Metadata: {len(metadata_list)} assets[/bold]")

        success = 0
        for idx, meta in enumerate(metadata_list):
            console.print(f"\n  [{idx + 1}/{len(metadata_list)}] {meta.filename}")

            # Click on asset tile
            for sel in self.cfg.asset_tile_selector:
                try:
                    tile = page.locator(sel).filter(has_text=meta.filename).first
                    if tile.is_visible(timeout=2000):
                        tile.click()
                        page.wait_for_timeout(1000)
                        break
                except Exception:
                    continue

            # Title
            title_val = getattr(meta, title_field, str(meta))
            self._fill_field(self.cfg.title_selector, str(title_val)[:200], "Title")

            # Keywords
            kw_val = getattr(meta, keywords_field, [])
            kw_text = ", ".join(kw_val) if isinstance(kw_val, list) else str(kw_val)
            self._fill_field(self.cfg.keywords_selector, kw_text, "Keywords")

            # AI checkbox
            ai_val = getattr(meta, "ai_generated", ai_generated)
            if ai_val:
                ai_el = self._find_visible(self.cfg.ai_checkbox_selector)
                if ai_el:
                    try:
                        if not ai_el.is_checked():
                            ai_el.click()
                            console.print("  ✓ AI Generated: checked")
                    except Exception:
                        console.print("  [yellow]⚠ Could not toggle AI checkbox[/yellow]")
                else:
                    console.print("  [yellow]⚠ AI checkbox not found[/yellow]")

            console.print(f"  [green]✓[/green] {meta.filename} metadata filled")
            success += 1

        return success

    # ── FULL PIPELINE ─────────────────────────────────────────

    def run(
        self,
        metadata_list: list,
        file_paths: list[str] | None = None,
        email: str = "",
        password: str = "",
        skip_upload: bool = False,
        skip_metadata: bool = False,
    ) -> int:
        """
        Full pipeline: login → upload → metadata → manual submit.
        Returns number of assets processed.
        """
        # Step 1: Login
        logged_in = self.login(email=email, password=password)
        if not logged_in:
            console.print("[yellow]⚠ Continuing with potentially unauthenticated session[/yellow]")

        # Step 2: Upload files
        files_uploaded = 0
        if file_paths and not skip_upload:
            files_uploaded = self.upload_files(file_paths)

            # ── CONFIRMATION NODE: Review upload ──
            self.confirm_node(
                CONFIRM_NODE_UPLOAD,
                "Files have been uploaded. Please review them in the browser.\n"
                "  • Check that all files appear correctly\n"
                "  • Make sure there are no errors\n"
                "  • If files are missing, upload them manually now",
                timeout_minutes=5,
            )

        # Step 3: Fill metadata
        processed = 0
        if metadata_list and not skip_metadata:
            processed = self.fill_metadata(metadata_list)

        # ── CONFIRMATION NODE: Manual submit ──
        if self.platform_name == "freepik":
            submit_msg = (
                "Files have been uploaded to Freepik.\n"
                "  • Please click 'Import CSV' (or 'Import metadata from CSV') in the browser.\n"
                "  • Select the output/metadata_freepik.csv file from your project.\n"
                "  • Verify that the titles, keywords, prompt, and model are correctly filled.\n"
                "  • Click Submit / Publish when ready."
            )
        else:
            submit_msg = (
                "All metadata has been filled.\n"
                "  • Review each asset in the browser\n"
                "  • Check title, keywords, and AI tag\n"
                "  • Click 'Submit' / 'Submit All' when ready\n"
                "  • Assets are NOT submitted until you do this"
            )
        
        self.confirm_node(
            CONFIRM_NODE_SUBMIT,
            submit_msg,
            timeout_minutes=10,
        )

        console.print(f"\n[bold green]✓ Pipeline complete[/bold green]")
        console.print(f"  Files uploaded: {files_uploaded}")
        console.print(f"  Metadata filled: {processed}/{len(metadata_list)}")

        return processed
